// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDosWSRBBLCNk5SZh0XxPJprge_yiZmqG0',
    appId: '1:1099476092311:web:fd79693496e82c171cb0d2',
    messagingSenderId: '1099476092311',
    projectId: 'chat-ecc-18252',
    authDomain: 'chat-ecc-18252.firebaseapp.com',
    storageBucket: 'chat-ecc-18252.firebasestorage.app',
    measurementId: 'G-9MNS6KRT54',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQXhacSFES7QBm2_fCV8coEXFd2_ElPEQ',
    appId: '1:1099476092311:android:8e0c3bae146c7c921cb0d2',
    messagingSenderId: '1099476092311',
    projectId: 'chat-ecc-18252',
    storageBucket: 'chat-ecc-18252.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABmtMuY-tFGXNccwfyBY5AZ4P_4oIP9zA',
    appId: '1:1099476092311:ios:2f2c5ac515fd73441cb0d2',
    messagingSenderId: '1099476092311',
    projectId: 'chat-ecc-18252',
    storageBucket: 'chat-ecc-18252.firebasestorage.app',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABmtMuY-tFGXNccwfyBY5AZ4P_4oIP9zA',
    appId: '1:1099476092311:ios:2f2c5ac515fd73441cb0d2',
    messagingSenderId: '1099476092311',
    projectId: 'chat-ecc-18252',
    storageBucket: 'chat-ecc-18252.firebasestorage.app',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDosWSRBBLCNk5SZh0XxPJprge_yiZmqG0',
    appId: '1:1099476092311:web:7af59043df64302c1cb0d2',
    messagingSenderId: '1099476092311',
    projectId: 'chat-ecc-18252',
    authDomain: 'chat-ecc-18252.firebaseapp.com',
    storageBucket: 'chat-ecc-18252.firebasestorage.app',
    measurementId: 'G-8J5979H5Q6',
  );
}
